# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{inkan}
  s.version = "1.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Pat Allan"]
  s.date = %q{2011-07-18}
  s.description = %q{}
  s.email = %q{pat@freelancing-gods.com}
  s.extra_rdoc_files = [
    "README.textile"
  ]
  s.files = [
    "LICENCE",
    "README.textile",
    "lib/inkan.rb"
  ]
  s.homepage = %q{http://github.com/freelancing-god/inkan}
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Unique file markers for tracking whether files have been changed.}
  s.test_files = [
    "spec/inkan_spec.rb",
    "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<jeweler>, ["= 1.5.1"])
      s.add_development_dependency(%q<yard>, ["= 0.6.1"])
      s.add_development_dependency(%q<rspec>, ["= 2.6.0"])
      s.add_development_dependency(%q<rcov>, ["= 0.9.8"])
    else
      s.add_dependency(%q<jeweler>, ["= 1.5.1"])
      s.add_dependency(%q<yard>, ["= 0.6.1"])
      s.add_dependency(%q<rspec>, ["= 2.6.0"])
      s.add_dependency(%q<rcov>, ["= 0.9.8"])
    end
  else
    s.add_dependency(%q<jeweler>, ["= 1.5.1"])
    s.add_dependency(%q<yard>, ["= 0.6.1"])
    s.add_dependency(%q<rspec>, ["= 2.6.0"])
    s.add_dependency(%q<rcov>, ["= 0.9.8"])
  end
end

